# Generated by Django 4.1.7 on 2023-03-02 13:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to='')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Independent'), (2, 'Organization')], default=1, null=True)),
                ('verification_code', models.IntegerField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('social_media_link', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('weekday_from', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], unique=True)),
                ('weekday_to', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('hide_email', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('organizer', models.CharField(max_length=200)),
                ('organizer_id', models.CharField(max_length=200, null=True)),
                ('organizer_profile_picture', models.CharField(blank=True, max_length=100, null=True)),
                ('event_date', models.CharField(max_length=50)),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('web_link', models.CharField(blank=True, max_length=100, null=True)),
                ('traffic', models.IntegerField(blank=True, default=0)),
                ('tickets', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'Concerts',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('client_profile_picture', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Requests',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'In Progress'), (2, 'In Review'), (3, 'Done')], default=1, max_length=25, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('organizer_id', models.CharField(max_length=100)),
                ('organizer', models.CharField(max_length=200)),
                ('organizer_profile_picture', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('permit', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('web_link', models.CharField(blank=True, max_length=100, null=True)),
                ('traffic', models.IntegerField(blank=True, default=0)),
                ('requests', models.ManyToManyField(blank=True, null=True, to='api.request')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='concerts',
            field=models.ManyToManyField(blank=True, null=True, to='api.concert'),
        ),
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='account',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='api.service'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
