# Generated by Django 4.1.7 on 2023-03-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='concert_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
