# Generated by Django 4.1.7 on 2023-03-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='concert',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.concert'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='service',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.service'),
        ),
    ]
