# Generated by Django 4.1.7 on 2023-03-09 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_favorite_created_at_favorite_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='concert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.concert'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.service'),
        ),
    ]
