# Generated by Django 4.1.7 on 2023-03-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_account_weekday_from_alter_account_weekday_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='weekday_from',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True, unique=True),
        ),
    ]
