# Generated by Django 4.1.7 on 2023-03-15 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_favoriteconcert_favoriteservice_delete_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='request',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='request',
            name='client_profile_picture',
        ),
        migrations.RemoveField(
            model_name='request',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='request',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='request',
            name='service_title',
        ),
        migrations.AddField(
            model_name='request',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.service'),
        ),
        migrations.AddField(
            model_name='request',
            name='viewed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
