# Generated by Django 4.1.7 on 2023-03-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_account_weekday_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='from_hour',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='to_hour',
            field=models.TimeField(null=True),
        ),
    ]
