# Generated by Django 4.1.7 on 2023-03-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_account_from_hour_alter_account_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='concerts',
            field=models.ManyToManyField(blank=True, to='api.concert'),
        ),
        migrations.AlterField(
            model_name='account',
            name='services',
            field=models.ManyToManyField(blank=True, to='api.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='requests',
            field=models.ManyToManyField(blank=True, to='api.request'),
        ),
    ]
