# Generated by Django 4.1.7 on 2023-03-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_ticket_assignee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
    ]
