# Generated by Django 4.1.7 on 2023-03-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_account_concerts_alter_account_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'In Progress'), (2, 'In Review'), (3, 'Done')], default=1, null=True),
        ),
    ]
