# Generated by Django 4.1.7 on 2023-03-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='organizer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='concert',
            name='organizer_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
