# Generated by Django 4.1.7 on 2023-03-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_account_from_hour_alter_account_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='advertise',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='advertise',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
