# Generated by Django 4.1.7 on 2023-03-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_concert_organizer_alter_concert_organizer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='organizer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='organizer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
