# Generated by Django 4.1.7 on 2023-03-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='Service',
            new_name='service',
        ),
    ]
