# Generated by Django 4.1.7 on 2023-03-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_service_web_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='client_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='client_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Generate'), (2, 'In Progress'), (3, 'In Review'), (4, 'Done')], null=True),
        ),
    ]
