# Generated by Django 4.1.7 on 2023-03-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_service_complaint_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='reports',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='reports',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
