# Generated by Django 4.1.7 on 2023-03-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_account_weekday_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assignee',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assignee_email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assignee_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assignee_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assignee_picture',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='concert_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='concert_picture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
