# Generated by Django 4.1.7 on 2023-03-22 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_concert_reports_service_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=600)),
                ('concert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.concert')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concert_complainant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Concert Complaints',
            },
        ),
        migrations.CreateModel(
            name='ServiceComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=600)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_complainant', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
            options={
                'verbose_name_plural': 'Service Complaints',
            },
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
