# Generated by Django 4.1.7 on 2023-03-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_concertcomplaint_servicecomplaint_delete_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='from_hour',
            field=models.TimeField(blank=True, default='8:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='to_hour',
            field=models.TimeField(blank=True, default='17:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='weekday_from',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='weekday_to',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=5, null=True),
        ),
    ]
