# Generated by Django 4.1.7 on 2023-03-03 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_request_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='requests',
        ),
        migrations.AddField(
            model_name='request',
            name='service_requested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.service'),
        ),
    ]
