# Generated by Django 4.1.7 on 2023-03-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_service_requests_request_service_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='service_requested',
        ),
        migrations.AddField(
            model_name='request',
            name='service_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='request',
            name='service_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
