# Generated by Django 4.1.7 on 2023-03-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_request_service_requested_request_service_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='organizer_media_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
